### ISSUE TITLE
Koin compiler plugin is incompatible with Kotlin 2.4.0

### ISSUE THREAD

**Issue by ymontero-max** [InsertKoinIO/koin#2431]
**Describe the bug**

After upgrading Kotlin from `2.3.21` to `2.4.0`, the Android project no longer compiles when the Koin compiler Gradle plugin is applied. Compilation fails during Kotlin compiler plugin registration with a `ClassCastException` inside `KoinPluginComponentRegistrar`.

**To Reproduce**

1. Use an Android project with Koin annotations and the Koin compiler Gradle plugin.
2. Configure:
   - `kotlin = "2.4.0"`
   - `koin = "4.2.1"`
   - `koinCompilerPlugin = "1.0.0"`
3. Apply the plugin:

```kotlin
plugins {
    alias(libs.plugins.koin.compiler)
}
```

4. Run:

```bash
./gradlew :app:compileDebugKotlin
```

5. See the compiler failure:

```text
java.lang.ClassCastException:
org.jetbrains.kotlin.fir.extensions.FirExtensionRegistrarAdapter$Companion
cannot be cast to
org.jetbrains.kotlin.extensions.ProjectExtensionDescriptor

at org.koin.compiler.plugin.KoinPluginComponentRegistrar.registerExtensions(...)
```

**Expected behavior**

The project should compile successfully with Kotlin `2.4.0`, or the plugin should clearly report that Kotlin `2.4.0` is not supported yet instead of failing with an internal compiler/plugin `ClassCastException`.

**Koin module and version:**

```text
koin-android:4.2.1
koin-androidx-compose:4.2.1
koin-annotations:4.2.1
koin-compose-navigation3:4.2.1
io.insert-koin.compiler.plugin:1.0.0
```

Also tested:

```text
io.insert-koin.compiler.plugin:1.0.0-RC2
```

Same `ClassCastException`.

**Snippet or Sample project to help reproduce**

Version catalog:

```toml
[versions]
kotlin = "2.4.0"
koin = "4.2.1"
koinPlugin = "1.0.0"

[libraries]
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin" }

[plugins]
koin-compiler = { id = "io.insert-koin.compiler.plugin", version.ref = "koinPlugin" }
```

Gradle plugin usage:

```kotlin
plugins {
    alias(libs.plugins.koin.compiler)
}
```

Koin compiler config:

```kotlin
koinCompiler {
    userLogs = false
    debugLogs = false
    compileSafety = true
    skipDefaultValues = true
    unsafeDslChecks = true
}
```

Minimal annotation usage:

```kotlin
@Module
@ComponentScan("com.example")
class AppModule

@Single
class ExampleRepository

@KoinViewModel
class ExampleViewModel(
    private val repository: ExampleRepository
) : ViewModel()
```

Application:

```kotlin
@KoinApplication
class MyApplication : Application() {
    override fun onCreate() {
        super.onCreate()

        startKoin<MyApplication> {
            androidContext(this@MyApplication)
        }
    }
}
```

Workaround:

Downgrading Kotlin back to `2.3.21` with `io.insert-koin.compiler.plugin:1.0.0` makes the project compile again.

**Comment by fanqieVip** [comment]
> **描述这个错误**
> 
> 将Kotlin从`2.3.21`升级到`2.4.0`后，当应用Koin编译器Gradle插件时，Android项目不再编译。`KoinPluginComponentRegistrar`内部的`ClassCastException`注册Kotlin编译器插件期间编译失败。
> 
> **复制**
> 
> 重现行为的步骤：
> 
> 1. 使用带有Koin注释和Koin编译器Gradle插件的Android项目。
> 2. 配置：
>    * `kotlin = "2.4.0"`
>    * `koin = "4.2.1"`
>    * `koinCompilerPlugin = "1.0.0"`
> 3. 应用插件：
> 
> plugins {
>     alias(libs.plugins.koin.compiler)
> }
>  4. 运行：
> 
> ./gradlew :app:compileDebugKotlin
>  5. 查看编译器故障：
> 
> ```
> java.lang.ClassCastException:
> org.jetbrains.kotlin.fir.extensions.FirExtensionRegistrarAdapter$Companion
> cannot be cast to
> org.jetbrains.kotlin.extensions.ProjectExtensionDescriptor
> 
> at org.koin.compiler.plugin.KoinPluginComponentRegistrar.registerExtensions(...)
> ```
> 
> **预期行为**
> 
> 该项目应该使用Kotlin `2.4.0`成功编译，或者插件应该明确报告Kotlin `2.4.0`尚未受支持，而不是内部编译器/插件`ClassCastException`失败。
> 
> **Koin模块和版本：**
> 
> ```
> koin-android:4.2.1
> koin-androidx-compose:4.2.1
> koin-annotations:4.2.1
> koin-compose-navigation3:4.2.1
> io.insert-koin.compiler.plugin:1.0.0
> ```
> 
> 也测试了：
> 
> ```
> io.insert-koin.compiler.plugin:1.0.0-RC2
> ```
> 
> 相同的`ClassCastException`。
> 
> **帮助复制的片段或样本项目**
> 
> 版本目录：
> 
> [versions]
> kotlin = "2.4.0"
> koin = "4.2.1"
> koinPlugin = "1.0.0"
> 
> [libraries]
> koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
> koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
> koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin" }
> 
> [plugins]
> koin-compiler = { id = "io.insert-koin.compiler.plugin", version.ref = "koinPlugin" }
> Gradle插件的使用：
> 
> plugins {
>     alias(libs.plugins.koin.compiler)
> }
> Koin编译器配置：
> 
> koinCompiler {
>     userLogs = false
>     debugLogs = false
>     compileSafety = true
>     skipDefaultValues = true
>     unsafeDslChecks = true
> }
> 最少的注释使用：
> 
> @Module
> @ComponentScan("com.example")
> class AppModule
> 
> @Single
> class ExampleRepository
> 
> @KoinViewModel
> class ExampleViewModel(
>     private val repository: ExampleRepository
> ) : ViewModel()
> 申请：
> 
> @KoinApplication
> class MyApplication : Application() {
>     override fun onCreate() {
>         super.onCreate()
> 
>         startKoin<MyApplication> {
>             androidContext(this@MyApplication)
>         }
>     }
> }
> 变通办法：
> 
> 使用`io.insert-koin.compiler.plugin:1.0.0`将Kotlin降级回`2.3.21`，使项目再次编译。

I’m running into the exact same issue.

**Comment by Jessewb786** [comment]
I ran into this issue on rc2. I'm glad it's getting attention. I'm anxiously awaiting this update so that I can use swiftPMDependencies in my KMP project.

**Comment by skolson** [comment]
Just tried to upgrade to Kotlin 2.4.0, also using KOIN 4.2.1 with plugin io.kotzilla.kotzilla-plugin version 2.2.0, and the error seen is a little different to above, in case this is useful. Just like stated above, project builds fine with 2.3.21. Sync shows the expected warning:
```
[Kotzilla] Kotlin '2.4.0-release-281' is above the verified ceiling (2.3.x). Instrumentation will be applied but compatibility is not guaranteed. Update Kotzilla SDK for explicit 2.4.0-release-281 support.
```
Assemble project gets the internal compiler error:
```
Problem found: Kotlin compiler error (id: kotlin:compiler:error:compiler-error)
  Kotlin compiler error
    java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.com.intellij.openapi.extensions.ExtensionPointName org.jetbrains.kotlin.backend.common.extensions.IrGenerationExtension$Companion.getExtensionPointName()'
    	at io.kotzilla.gradle.kcp.KotzillaPluginRegistrar.registerProjectComponents(KotzillaPluginRegistrar.kt:40)
    	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.registerExtensionsFromPlugins$org_jetbrains_kotlin_cli_base(KotlinCoreEnvironment.kt:741)
    	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$ProjectEnvironment.registerExtensionsFromPlugins(KotlinCoreEnvironment.kt:182)
    	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.configureProjectEnvironment(KotlinCoreEnvironment.kt:644)
    	at org.jetbrains.kotlin.cli.jvm.compiler.legacy.pipeline.JvmCompilerPipelineKt.createProjectEnvironment(jvmCompilerPipeline.kt:199)
    	at org.jetbrains.kotlin.cli.pipeline.jvm.JvmFrontendPipelinePhase.createEnvironmentAndSources(JvmFrontendPipelinePhase.kt:202)
    	at org.jetbrains.kotlin.cli.pipeline.jvm.JvmFrontendPipelinePhase.executePhase(JvmFrontendPipelinePhase.kt:68)
    	at org.jetbrains.kotlin.cli.pipeline.jvm.JvmFrontendPipelinePhase.executePhase(JvmFrontendPipelinePhase.kt:51)
    	at org.jetbrains.kotlin.cli.pipeline.PipelinePhase.phaseBody(PipelinePhase.kt:63)
    	at org.jetbrains.kotlin.cli.pipeline.PipelinePhase.phaseBody(PipelinePhase.kt:53)
    	at org.jetbrains.kotlin.config.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:102)
    	at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:22)
    	at org.jetbrains.kotlin.config.phaser.CompilerPhaseKt.invokeToplevel(CompilerPhase.kt:53)
    	at org.jetbrains.kotlin.cli.pipeline.AbstractCliPipeline.runPhasedPipeline(AbstractCliPipeline.kt:135)
    	at org.jetbrains.kotlin.cli.pipeline.AbstractCliPipeline.executeAndReturnPipeLineArtifact(AbstractCliPipeline.kt:89)
    	at org.jetbrains.kotlin.cli.pipeline.AbstractCliPipeline.executeAndReturnPipeLineArtifact$default(AbstractCliPipeline.kt:49)
    	at org.jetbrains.kotlin.cli.pipeline.AbstractCliPipeline.execute(AbstractCliPipeline.kt:40)
    	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecutePhased(K2JVMCompiler.kt:54)
    	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecutePhased(K2JVMCompiler.kt:45)
    	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:94)
    	at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.kt:366)
    	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunnerBase.runCompiler(IncrementalJvmCompilerRunnerBase.kt:211)
    	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunnerBase.runCompiler(IncrementalJvmCompilerRunnerBase.kt:53)
    	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.doCompile(IncrementalCompilerRunner.kt:539)
    	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:451)
    	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileNonIncrementally(IncrementalCompilerRunner.kt:327)
    	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:139)
    	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:782)
    	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:108)
    	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:2046)
    	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
    	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
    	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(Unknown Source)
    	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
    	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
    	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
    	at java.rmi/sun.rmi.transport.Transport.serviceCall(Unknown Source)
    	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
    	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)
    	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(Unknown Source)
    	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
    	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by cloudigits** [comment]
Any update

**Comment by skolson** [comment]
I'm still seeing this error after updating (I thought :-) to 2.2.2 and 1.01 using Kotlin 2.4.0.  The lines from libs.versions.toml
```
koin = "4.2.1"
koinPlugin = "1.0.1"
kotzilla = "2.2.2"

...
[plugins]
kotzilla = { id = "io.kotzilla.kotzilla-plugin", version.ref = "kotzilla" }
koin-plugin = { id = "io.insert-koin.compiler.plugin", version.ref = "koinPlugin" }
```
Sync works but after a clean, assemble project gets the same error:
```
Problem found: Kotlin compiler error (id: kotlin:compiler:error:compiler-error)
  Kotlin compiler error
    java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.com.intellij.openapi.extensions.ExtensionPointName org.jetbrains.kotlin.backend.common.extensions.IrGenerationExtension$Companion.getExtensionPointName()'
    	at io.kotzilla.gradle.kcp.KotzillaPluginRegistrar.registerProjectComponents(KotzillaPluginRegistrar.kt:40)

```

It also displays the same warning up front:
```
[Kotzilla] Kotlin '2.4.0-release-281' is above the verified ceiling (2.3.x). Instrumentation will be applied but compatibility is not guaranteed. Update Kotzilla SDK for explicit 2.4.0-release-281 support.
```

Shouldn't this work after the recent updates? Is there a way to verify I'm using the correct updates from a couple days ago? Or am I just doing something wrong :-)

**Comment by EarzuChan** [comment]
Same with me, while using Kotlin 2.4.0, Koin 4.2.2, Koin Compiler Plugin 1.0.0

java.lang.ClassCastException: class org.jetbrains.kotlin.fir.extensions.FirExtensionRegistrarAdapter$Companion cannot be cast to class org.jetbrains.kotlin.extensions.ProjectExtensionDescriptor (org.jetbrains.kotlin.fir.extensions.FirExtensionRegistrarAdapter$Companion and org.jetbrains.kotlin.extensions.ProjectExtensionDescriptor are in unnamed module of loader 'app') at org.koin.compiler.plugin.KoinPluginComponentRegistrar.registerExtensions(KoinPluginComponentRegistrar.kt:328)

When updated to Koin Compiler Plugin 1.0.1, it's gone

**Comment by ymontero-max** [comment]
Koin 4.2.2 and Koin Compiler Plugin 1.0.1 are now available
