### ISSUE TITLE
[Android] scope crash

### ISSUE THREAD

**Issue by pouyamiralayi** [InsertKoinIO/koin#700]
Using the scope feature will cause application to crash with the following error at startup:
```
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/koin/core/definition/DefinitionFactory;
        at com.myexample.di.module.ModulesKt$appModule$1$20.invoke(modules.kt:362)
        at com.myexample.di.module.ModulesKt$appModule$1$20.invoke(Unknown Source:2)
        at org.koin.core.module.Module.scope(Module.kt:48)
        at com.myexample.di.module.ModulesKt$appModule$1.invoke(modules.kt:137)
        at com.myexample.di.module.ModulesKt$appModule$1.invoke(Unknown Source:2)
        at org.koin.dsl.ModuleKt.module(Module.kt:31)
        at org.koin.dsl.ModuleKt.module$default(Module.kt:29)
        at com.myexample.di.module.ModulesKt.<clinit>(modules.kt:60)
        at com.myexample.di.module.ModulesKt.getAppModule(modules.kt:60)
        at com.myexample.AppLockerApplication$onCreate$1.invoke(AppLockerApplication.kt:35)
        at com.myexample.AppLockerApplication$onCreate$1.invoke(AppLockerApplication.kt:20)
        at org.koin.core.context.GlobalContextKt.startKoin(GlobalContext.kt:73)
        at com.myexample.AppLockerApplication.onCreate(AppLockerApplication.kt:31)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.koin.core.definition.DefinitionFactory" on path: DexPathList[[zip file "/data/app/com.myexample.dev-z7fdQIUIoJy0FQTcCoV62g==/base.apk"],nativeLibraryDirectories=[/data/app/com.myexample.dev-z7fdQIUIoJy0FQTcCoV62g==/lib/x86_64, /data/app/com.myexample.dev-z7fdQIUIoJy0FQTcCoV62g==/base.apk!/lib/x86_64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

**Steps to reproduce the behavior:**
1. Define a scope in your module as the following:
```
scope(named("permission")) {
        scoped { PermissionDataProvider(get(), get()) }
        scoped {
            get<AppDatabase>().getPermissionDao()
        }
        factory { PermissionListViewStateCreator(get()) }
        scoped { PermissionListFragment() } 
        viewModel { PermissionListViewModel(get(), get(), get(), get()) }
        viewModel { PermissionViewModel(get(), get()) }
    }
```
2. Build & Run
3. See error

**Expected behavior**
App launches normally.

` koin_version = "2.0.1"`
`koin_version_unstable = "2.1.0-alpha-8"`
```
    implementation "org.koin:koin-core:$koin_version"
    implementation "org.koin:koin-core-ext:$koin_version"
    implementation "org.koin:koin-android:$koin_version"
    implementation "org.koin:koin-android-scope:$koin_version"
    implementation "org.koin:koin-android-viewmodel:$koin_version"
    implementation "org.koin:koin-android-ext:$koin_version"
    implementation "org.koin:koin-androidx-scope:$koin_version"
    implementation "org.koin:koin-androidx-viewmodel:$koin_version"
    implementation "org.koin:koin-androidx-fragment:$koin_version_unstable"
```

**Additional moduleDefinition**
```
val appModule = module {
    single {
        Room.databaseBuilder(
            get(), AppDatabase::class.java,
            DB_NAME
        )
            .addMigrations(
                AppDatabase.MIGRATION_1_2,
                AppDatabase.MIGRATION_2_3,
                AppDatabase.MIGRATION_3_4,
                AppDatabase.MIGRATION_4_5
            )
            .build()
    }


    scope(named("permission")) {
        scoped { PermissionDataProvider(get(), get()) }
        scoped {
            get<AppDatabase>().getPermissionDao()
        }
        factory { PermissionListViewStateCreator(get()) }
        scoped { PermissionListFragment() } 
        viewModel { PermissionListViewModel(get(), get(), get(), get()) }
        viewModel { PermissionViewModel(get(), get()) }
    }
}

class PermissionActivity : BaseActivity<PermissionViewModel>("permission") {
    private lateinit var binding: ActivityPermissionBinding

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        binding = DataBindingUtil.setContentView(this, R.layout.activity_permission)

        if (savedInstanceState == null) {
            supportFragmentManager.beginTransaction()
                .add(
                    R.id.containerPermission,
                    PermissionListFragment::class.java,
                    null,
                    null
                )
                .commitAllowingStateLoss()
        }

        binding.imageViewBack.setOnClickListener {
            finish()
        }
    }

    companion object {
        fun newIntent(context: Context) = Intent(context, PermissionActivity::class.java)
    }
}

abstract class BaseActivity<VM : ViewModel> constructor(scopeId: String) :
    AppCompatActivity() {

    protected val session = getKoin().createScope(scopeId, named(scopeId))
    protected val viewModel: VM by lazy { session.getViewModel(this, viewModelClass()) }


    override fun onCreate(savedInstanceState: Bundle?) {
        setupKoinFragmentFactory(currentScope)
        super.onCreate(savedInstanceState)
    }

    @Suppress("UNCHECKED_CAST")
    private fun viewModelClass(): KClass<VM> {
        return ((javaClass.genericSuperclass as ParameterizedType)
            .actualTypeArguments[0] as Class<VM>).kotlin
    }

    override fun onDestroy() {
        if (session.closed.not())
            session.closed
        super.onDestroy()
    }
}

class PermissionListFragment : BaseFragment<PermissionListViewModel>("permission") {

    private val binding: FragmentPermissionBinding by inflate(
        R.layout.fragment_permission
    )

    private val adapter: PermissionListAdapter =
        PermissionListAdapter()

    fun getViewModel(): Class<PermissionViewModel> = PermissionViewModel::class.java

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        binding.recyclerViewPermissionList.adapter = adapter

        return binding.root
    }

    override fun onActivityCreated(savedInstanceState: Bundle?) {
        super.onActivityCreated(savedInstanceState)

        viewModel.getPermissionListLiveData().observe(viewLifecycleOwner, Observer {
            adapter.addToAppDataList(it)
        })

        viewModel.getLoadingVisibility().observe(viewLifecycleOwner, Observer {
            binding.progress.visibility = it
        })
    }

}

abstract class BaseFragment<VM : ViewModel> constructor(scopeId: String) : Fragment() {

    protected val session = getKoin().getOrCreateScope(scopeId, named(scopeId))
    protected val viewModel: VM by lazy {
        session.getViewModel(
            viewLifecycleOwner,
            viewModelClass()
        )
    }


    protected val appLockerPreferences by inject<AppLockerPreferences>()


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
    }

    @Suppress("UNCHECKED_CAST")
    private fun viewModelClass(): KClass<VM> {
        return ((javaClass.genericSuperclass as ParameterizedType)
            .actualTypeArguments[0] as Class<VM>).kotlin
    }
}
```

**Additional context**
The app works fine without scope.

Cheers!

**Comment by ligi** [comment]
Also just had this crash after updating from Koin 2.0.1 to 2.1.1. Fun fact: I do not use scopes in this app.

```
2020-03-01 18:42:27.238 5273-5273/org.walleth.offline E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.walleth.offline, PID: 5273
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/koin/core/definition/DefinitionFactory;
        at org.walleth.infrastructure.TestApp$createKoin$1.invoke(TestApp.kt:528)
        at org.walleth.infrastructure.TestApp$createKoin$1.invoke(TestApp.kt:48)
        at org.koin.dsl.ModuleKt.module(Module.kt:31)
        at org.koin.dsl.ModuleKt.module$default(Module.kt:29)
        at org.walleth.infrastructure.TestApp.createKoin(TestApp.kt:50)
        at org.walleth.App$onCreate$1.invoke(App.kt:150)
        at org.walleth.App$onCreate$1.invoke(App.kt:67)
        at org.koin.core.context.ContextFunctionsKt.startKoin(ContextFunctions.kt:39)
        at org.koin.core.context.ContextFunctionsKt.startKoin$default(ContextFunctions.kt:35)
        at org.walleth.App.onCreate(App.kt:147)
        at org.walleth.infrastructure.TestApp.onCreate(TestApp.kt:88)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at androidx.test.runner.MonitoringInstrumentation.callApplicationOnCreate(MonitoringInstrumentation.java:419)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.koin.core.definition.DefinitionFactory" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/data/app/org.walleth.offline.test-sqC8vH90PTJOU41YMfRUCA==/base.apk", zip file "/data/app/org.walleth.offline-cSVkZZEOxB0Nksd0IDEsgw==/base.apk"],nativeLibraryDirectories=[/data/app/org.walleth.offline.test-sqC8vH90PTJOU41YMfRUCA==/lib/x86_64, /data/app/org.walleth.offline-cSVkZZEOxB0Nksd0IDEsgw==/lib/x86_64, /data/app/org.walleth.offline.test-sqC8vH90PTJOU41YMfRUCA==/base.apk!/lib/x86_64, /data/app/org.walleth.offline-cSVkZZEOxB0Nksd0IDEsgw==/base.apk!/lib/x86_64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.walleth.infrastructure.TestApp$createKoin$1.invoke(TestApp.kt:528) 
        at org.walleth.infrastructure.TestApp$createKoin$1.invoke(TestApp.kt:48) 
        at org.koin.dsl.ModuleKt.module(Module.kt:31) 
        at org.koin.dsl.ModuleKt.module$default(Module.kt:29) 
        at org.walleth.infrastructure.TestApp.createKoin(TestApp.kt:50) 
        at org.walleth.App$onCreate$1.invoke(App.kt:150) 
        at org.walleth.App$onCreate$1.invoke(App.kt:67) 
        at org.koin.core.context.ContextFunctionsKt.startKoin(ContextFunctions.kt:39) 
        at org.koin.core.context.ContextFunctionsKt.startKoin$default(ContextFunctions.kt:35) 
        at org.walleth.App.onCreate(App.kt:147) 
        at org.walleth.infrastructure.TestApp.onCreate(TestApp.kt:88) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154) 
        at androidx.test.runner.MonitoringInstrumentation.callApplicationOnCreate(MonitoringInstrumentation.java:419) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 

```

**Comment by adeelturk** [comment]
Same issue 
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/koin/core/definition/DefinitionFactory;
        at com.tatweer.invechicleapp.common.infrastructure.arch.ViewModelModuleKt$viewModelsModule$1.invoke(ViewModelModule.kt:60)
        at com.tatweer.invechicleapp.common.infrastructure.arch.ViewModelModuleKt$viewModelsModule$1.invoke(Unknown Source:2)
        at org.koin.dsl.ModuleKt.module(Module.kt:31)
        at org.koin.dsl.ModuleKt.module$default(Module.kt:29)
        at com.tatweer.invechicleapp.common.infrastructure.arch.ViewModelModuleKt.<clinit>(ViewModelModule.kt:21)
        at com.tatweer.invechicleapp.common.infrastructure.arch.ViewModelModuleKt.getViewModelsModule(ViewModelModule.kt:21)
        at com.tatweer.invechicleapp.IpvApplication$onCreate$1.invoke(IpvApplication.kt:51)
        at com.tatweer.invechicleapp.IpvApplication$onCreate$1.invoke(IpvApplication.kt:28)
        at org.koin.core.context.ContextFunctionsKt.startKoin(ContextFunctions.kt:39)
        at org.koin.core.context.ContextFunctionsKt.startKoin$default(ContextFunctions.kt:35)
        at com.tatweer.invechicleapp.IpvApplication.onCreate(IpvApplication.kt:32)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
        at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7036)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6989)
        at android.app.ActivityThread.access$1600(ActivityThread.java:272)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2055)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8016)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.koin.core.definition.DefinitionFactory" on path: DexPathList[[zip file "/data/app/com.tatweer.invechicleapp.dev-CMQsIskO9pCtypQ0AUKHEQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.tatweer.invechicleapp.dev-CMQsIskO9pCtypQ0AUKHEQ==/lib/arm, /data/app/com.tatweer.invechicleapp.dev-CMQsIskO9pCtypQ0AUKHEQ==/base.apk!/lib/armeabi-v7a, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.tatweer.invechicleapp.common.infrastructure.arch.ViewModelModuleKt$viewModelsModule$1.invoke(ViewModelModule.kt:60) 
        at com.tatweer.invechicleapp.common.infrastructure.arch.ViewModelModuleKt$viewModelsModule$1.invoke(Unknown Source:2) 
        at org.koin.dsl.ModuleKt.module(Module.kt:31) 
        at org.koin.dsl.ModuleKt.module$default(Module.kt:29) 
        at com.tatweer.invechicleapp.common.infrastructure.arch.ViewModelModuleKt.<clinit>(ViewModelModule.kt:21) 
        at com.tatweer.invechicleapp.common.infrastructure.arch.ViewModelModuleKt.getViewModelsModule(ViewModelModule.kt:21) 
        at com.tatweer.invechicleapp.IpvApplication$onCreate$1.invoke(IpvApplication.kt:51) 
        at com.tatweer.invechicleapp.IpvApplication$onCreate$1.invoke(IpvApplication.kt:28) 
        at org.koin.core.context.ContextFunctionsKt.startKoin(ContextFunctions.kt:39) 
        at org.koin.core.context.ContextFunctionsKt.startKoin$default(ContextFunctions.kt:35) 
        at com.tatweer.invechicleapp.IpvApplication.onCreate(IpvApplication.kt:32) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190) 
        at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7036) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6989) 
        at android.app.ActivityThread.access$1600(ActivityThread.java:272) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2055) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:8016) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
