### ISSUE TITLE
Migration from 2.2.3 to 3.1.5 crashes at runtime with NoSuchMethodError

### ISSUE THREAD

**Issue by emmaChristine** [InsertKoinIO/koin#1272]
**Describe the bug**
After updating to 3.1.5 I get this runtime error:
java.lang.NoSuchMethodError: No static method module$default(ZLkotlin/jvm/functions/Function1;ILjava/lang/Object;)Lorg/koin/core/module/Module; in class Lorg/koin/dsl/ModuleKt; or its super classes 

I didn't change the way we startKoin in main application:
```
class MainApplication: Application {

  override fun onCreate() {
  super.onCreate()
  startKoin {
      androidContext(this@MainApplication)
     modules(.....)
   }
.......

```

**To Reproduce**
I have tried all combinations of the following dependencies, with no luck
```
    implementation("io.insert-koin:koin-core:3.1.5")
    implementation("io.insert-koin:koin-core-ext:3.0.2")
    implementation("io.insert-koin:koin-android:3.1.5")
    implementation("io.insert-koin:koin-android-ext:3.0.2")
```

**Comment by arnaudgiuliani** [comment]
Hello,

as a first step, try to remove both "core-ext" and "android-ext" dependencies

**Comment by mochadwi** [comment]
any updates? @emmaChristine

**Comment by arnaudgiuliani** [comment]
yes, those dependencies are not in Koin 3.1 anymore. Also be sure to use the right Kotlin version: 1.5.x with koin 3.1
