### ISSUE TITLE
Android Compose beta07 + koin android-compose 3.0.1 

### ISSUE THREAD

**Issue by Shusshu** [InsertKoinIO/koin#1098]
**Describe the bug**
java.lang.NoSuchMethodError: No interface method startReplaceableGroup(ILjava/lang/String;)V in class Landroidx/compose/runtime/Composer; or its super classes (declaration of 'androidx.compose.runtime.Composer' appears in /data/app/~~hoqT5_6RjBVhoNulom1tuw==/com.itsdino.app.debug-2kwHw6G8w8Cw3TSpBQ--dw==/base.apk)
      

**To Reproduce**
I'm trying to inject Coil's ImageLoader into my composable

    @Composable
    fun MyComposable(
        imageLoader: ImageLoader = get()
    )

It crashes on the `get()` part

Maybe it's due to a version issue

    Note: Libraries dependent on Compose will need to recompile with version 1.0.0‑beta07. Otherwise, libraries may encounter a NoSuchMethodError, such as:
    java.lang.NoSuchMethodError: No interface method startReplaceableGroup(ILjava/lang/String;)V in class Landroidx/compose/runtime/Composer; or its super classes. (Ia34e6)

https://developer.android.com/jetpack/androidx/releases/compose-foundation?authuser=1#1.0.0-beta07

So I created a PR to update the version which means we'll also need a snapshot or a new release on maven central

Note: compose is not yet compatible with kotlin 1.5.0 thus koin's 3.0.2 branch will not help

**Expected behavior**
Injects the property into my composable

**Koin project used and used version (please complete the following information):**
AndroidxCompose beta07 + koin android-compose 3.0.1

**Comment by Shusshu** [comment]
https://github.com/InsertKoinIO/koin/pull/1102 is the new PR for this issue.

**Comment by hackdie** [comment]
Hi guys anyone have any update here, or how to use beta07 with Koin 3.0.1?

**Comment by mirecalu** [comment]
Hi, any workaround ?

**Comment by Shusshu** [comment]
beta08 is out

**Comment by Shusshu** [comment]
compose beta08 is out and is compatible with kotlin 1.5.0

**Comment by arnaudgiuliani** [comment]
beta08 will be added

**Comment by mtangoo** [comment]
Still facing same issue with compose 1.1.1 and koin compose 3.0.1

**Comment by mtangoo** [comment]
Updatiing to 3.2 beta 1 solved the issue
`implementation "io.insert-koin:koin-androidx-compose:3.2.0-beta-1"
`
