### ISSUE TITLE
Not supporting Ktor 1.6.6

### ISSUE THREAD

**Issue by emirhanemmez** [InsertKoinIO/koin#1243]
When i upgrade ktor version 1.6.5 to 1.6.6 this error occurs:

Exception in thread "main" java.lang.NoSuchMethodError: 'double kotlin.time.Duration.toDouble-impl(long, java.util.concurrent.TimeUnit)'

This error same as well in #1188

**Comment by ahmedtanjim** [comment]
same to me

**Comment by ericchuawc** [comment]
Same here on 1.6.7

I followed the suggestion here and managed to run it

https://youtrack.jetbrains.com/issue/KTOR-3575

**Comment by arnaudgiuliani** [comment]
after Ktor 1.6.5, it pulls Kotlin 1.6 which breaks a time measurement API in Koin. Ktor 1.6.7 and later will follow in Koin 3.2 branch

**Comment by arnaudgiuliani** [comment]
we need to stay at ktor 1.6.5 for Koin 3.1. We are decoupling koin-ktor project to have its own cycle and better follow Ktor/Kotlin versions.
