### ISSUE TITLE
Koin 2.2.2 not working with Compose alpha12

### ISSUE THREAD

**Issue by igorescodro** [InsertKoinIO/koin#1006]
After upgrading Jetpack Compose dependency to alpha12 and Kotlin to 1.4.30, Koin does not work with following message:

`Class 'org.koin.androidx.compose.ViewModelComposeExtKt' is compiled by an unstable version of the Kotlin compiler and cannot be loaded by this compiler`

Branch reproducing the issue:
https://github.com/igorescodro/alkaa/tree/update/compose

**Comment by solcott** [comment]
This is also happening with 3.0.1-alpha-3.

**Comment by solcott** [comment]
The workaround is to add the `-Xallow-unstable-dependencies` compiler arg.

```
//build.gradle
kotlinOptions {
    jvmTarget = '1.8'
    useIR = true
    freeCompilerArgs += "-Xallow-unstable-dependencies"
}
```

```
//build.gradle.kts
kotlinOptions {
    jvmTarget = JavaVersion.VERSION_1_8.toString()
    useIR = true
    freeCompilerArgs = listOf(
      "-Xallow-unstable-dependencies"
    )
  }
```

**Comment by solcott** [comment]
Looks like the workaround only fixes compilation issue.  At runtime I get
```
Found interface androidx.compose.runtime.Composer, but class was expected (declaration of 'androidx.compose.runtime.Composer' appears
```

Composer was changed to an interface in 1.0.0-alpha12.  https://android-review.googlesource.com/c/platform/frameworks/support/+/1553151. This was a binary breaking change.

**Comment by joharei** [comment]
Another workaround that also works at runtime is to copy the content from [`ViewModelComposeExt`](https://github.com/InsertKoinIO/koin/blob/master/android-compose/koin-androidx-compose/src/main/java/org/koin/androidx/compose/ViewModelComposeExt.kt) and [`ComposeExt`](https://github.com/InsertKoinIO/koin/blob/master/android-compose/koin-androidx-compose/src/main/java/org/koin/androidx/compose/ComposeExt.kt) to your own project, update them to work with the latest Compose version and compile.

**Comment by noahjutz** [comment]
I can confirm this works. For anyone wondering, here's exactly how to do it:

Step 1: Create a kotlin file containing all the code from [`ViewModelComposeExt`](https://github.com/InsertKoinIO/koin/blob/master/android-compose/koin-androidx-compose/src/main/java/org/koin/androidx/compose/ViewModelComposeExt.kt) and [`ComposeExt`](https://github.com/InsertKoinIO/koin/blob/master/android-compose/koin-androidx-compose/src/main/java/org/koin/androidx/compose/ComposeExt.kt):

<details>
  <summary>KoinComposeWorkaround.kt</summary>
  
  ```kotlin
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.platform.AmbientViewModelStoreOwner
import androidx.lifecycle.ViewModel
import org.koin.androidx.viewmodel.ViewModelOwner.Companion.from
import org.koin.androidx.viewmodel.koin.getViewModel
import org.koin.core.Koin
import org.koin.core.context.GlobalContext
import org.koin.core.parameter.ParametersDefinition
import org.koin.core.qualifier.Qualifier

/**
 * Compose v1.0.0-alpha12 and koin v2.2.2 are not compatible. This file contains koin source code as
 * a temporary workaround.
 */

/**
 * Resolve ViewModel instance
 *
 * @param qualifier
 * @param parameters
 *
 * @author Arnaud Giuliani
 */
@Composable
inline fun <reified T : ViewModel> getViewModel(
    qualifier: Qualifier? = null,
    noinline parameters: ParametersDefinition? = null,
): T {
    val owner = AmbientViewModelStoreOwner.current.viewModelStore
    return remember {
        GlobalContext.get()
            .getViewModel(qualifier, owner = { from(owner) }, parameters = parameters)
    }
}

/**
 * Resolve a dependency for [Composable] functions
 * @param qualifier
 * @param parameters
 *
 * @return Lazy instance of type T
 *
 * @author Arnaud Giuliani
 * @author Henrique Horbovyi
 * @author Arnaud Giuliani
 */
@Composable
inline fun <reified T> get(
    qualifier: Qualifier? = null,
    noinline parameters: ParametersDefinition? = null,
): T = remember {
    GlobalContext.get().get(qualifier, parameters)
}

@Composable
fun getKoin(): Koin = remember {
    GlobalContext.get()
}
  ```
</details>

Step 2: Replace all imports of `get` and `getViewModel`. This can be done either manually or using `find` and `sed` on linux (replace `com.example.app` with your package name):

```bash
# get all file paths and write to temporary file
find . -name "*.kt" -exec readlink -f {} \; > ~/ktfiles
# replace getViewModel imports
sed -i 's/import org.koin.androidx.compose.getViewModel/import com.example.app.util.getViewModel/g' $(cat ~/tmpktfiles)
# replace get imports
sed -i 's/import org.koin.androidx.compose.get/import com.example.app.util.get/g' $(cat ~/tmpktfiles)
# remove temporary file
rm ~/tmpktfiles
```

**Comment by SYtor** [comment]
Also note that you need to add additional dependency for `LocalViewModelStoreOwner`
`implementation "androidx.lifecycle:lifecycle-viewmodel-compose:1.0.0-alpha02"`

**Comment by headsvk** [comment]
> Another workaround that also works at runtime is to copy the content from [`ViewModelComposeExt`](https://github.com/InsertKoinIO/koin/blob/master/android-compose/koin-androidx-compose/src/main/java/org/koin/androidx/compose/ViewModelComposeExt.kt) and [`ComposeExt`](https://github.com/InsertKoinIO/koin/blob/master/android-compose/koin-androidx-compose/src/main/java/org/koin/androidx/compose/ComposeExt.kt) to your own project, update them to work with the latest Compose version and compile.

@joharei this is a good solution that compiles but I'm getting a runtime exception `java.lang.NoSuchMethodError: No virtual method getRootScope()Lorg/koin/core/scope/ScopeDefinition; in class Lorg/koin/core/module/Module;`. I assume koin-androidx-viewmodel 3.0.0-alpha4 is not compatible with koin-core 3.0.1-alpha3. Did you manage to make it work with 3.0.1 or 2.2.2?

**Comment by joharei** [comment]
It works fine for me with compose beta01 and koin 2.2.2: https://github.com/joharei/nearby-mobility/blob/master/app/src/main/java/app/reitan/nearby_mobility/di/ViewModelComposeExt.kt

**Comment by headsvk** [comment]
I see, I'm using 3.0.1-alpha3 for multiplatform support but thanks for reply. I missed that `koin-androidx-viewmodel` was merged to `koin-android` in 3.0.1, now it's working for me too 🙂

**Comment by arnaudgiuliani** [comment]
Compose will follow only with Koin 3.0.x. Last 3.0.1 is compatible with beta01
