### PR TITLE
update jetpack-compose to 1.0.0-beta08

### PR DESCRIPTION
**Pull request by SergejIsbrecht**
## Actions
* update all compose dependencies to latest greatest
* rebased against origin/master (3.0.2)
* use `Kotlin` `1.4.32`, in Compose, because `Compose` is not compatible with 1.5
* run tests for android-compose (with ./test.sh)
* composite build with android project using jetpack-compose (seems to work)

## Description

Koin can not be used with newer Compose libraries, because of following issue:

```plain
Note: Libraries dependent on Compose will need to recompile with version 1.0.0‑beta07. Otherwise, libraries may encounter a NoSuchMethodError, such as:
java.lang.NoSuchMethodError: No interface method startReplaceableGroup(ILjava/lang/String;)V in class Landroidx/compose/runtime/Composer; or its super classes. (Ia34e6)
```

https://developer.android.com/jetpack/androidx/releases/compose-compiler#1.0.0-beta07

## Open points
Do not know how semantic versioning is applied in `Koin`, therefore I did not touch the versions. I would say it is a "major", because transitive dependencies changed in an incompatible ABI way. 

Please advice, if I change something which I shouldn't.

### CODE REVIEW

File: android-compose/koin-androidx-compose/build.gradle [hunk 1]
```diff
@@ -14,7 +13,7 @@ ext {
 
 android {
     compileSdkVersion 29
```
Comment (Shusshu) [inline android-compose/koin-androidx-compose/build.gradle:15]: You can target 30 too :)

**Comment by arnaudgiuliani** [comment]
This is on hold, need to figure out how they will solve the 1.5.0 compat issue.

**Comment by SergejIsbrecht** [comment]
@arnaudgiuliani :
> This is on hold, need to figure out how they will solve the 1.5.0 compat issue.

Which compat issue do you mean? When I have a look at the compat guide^1 for 1.5, it seems that 1.4 is fully binary compatible with 1.5. Up to now I do not know any reason not to use compiled 1.4 Kotlin classes with Kotlin 1.5. Could you please elaborate?

^1 https://kotlinlang.org/docs/compatibility-guide-15.html

**Comment by Shusshu** [comment]
Does koin really need kotlin 1.5.0? It could go back to 1.4.32...

**Comment by SergejIsbrecht** [comment]
Ok, looks like JC already supports Kotlin 1.5 on the master. One of the devs told me, that with the next JC release Kotlin 1.5 will be available:

https://twitter.com/intelligibabble/status/1397799382192300034

File: gradle/versions-android.gradle [hunk 2]
```diff
@@ -18,7 +18,6 @@ ext {
     
     androidx_workmanager = '2.5.0'
 
-    androidx_compose_gradle_version = "4.2.0-beta03" //"7.0.0-alpha08"
-    androidx_compose_version = "1.0.0-beta05"
-
+    androidx_compose_gradle_version = "7.1.0-alpha01" //"7.0.0-alpha08"
+    androidx_compose_version = "1.0.0-beta07"
```
Comment (Shusshu) [inline gradle/versions-android.gradle:22]: change to beta08

File: gradle/versions.gradle [hunk 3]
```diff
@@ -5,6 +5,7 @@ ext {
 
     // Kotlin
     kotlin_version = '1.5.0'
+    kotlin_version_compose = '1.4.32'
```
Comment (Shusshu) [inline gradle/versions.gradle:8]: take the other property

File: gradle/versions.gradle [hunk 4]
```diff
@@ -5,6 +5,7 @@ ext {
 
     // Kotlin
     kotlin_version = '1.5.0'
```
Comment (Shusshu) [inline gradle/versions.gradle:7]: kotlin 1.5.10

File: android-compose/build.gradle [hunk 5]
```diff
@@ -8,7 +8,7 @@ buildscript {
     }
     dependencies {
         // Kotlin
-        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
+        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version_compose"
```
Comment (Shusshu) [inline android-compose/build.gradle:11]: no longer needed

**Comment by SergejIsbrecht** [comment]
@Shusshu , did you try it with Kotlin 1.5? The changelog did not say anything about supporting Kotlin 1.5.

**Comment by boralyl** [comment]
@SergejIsbrecht The commits mention 1.5.0 https://android.googlesource.com/platform/frameworks/support/+log/b648147c5fdfc5ecbad57e40e2dc0c69aa23bf12..86ff5b4bb956431ec884586ce0aea0127e189ec4/compose/animation

**Comment by SergejIsbrecht** [comment]
@arnaudgiuliani , beta08 seems to be supporting Kotlin 1.5. There seems to be no official report stating Kotlin 1.5 is now supported. I had to lift the Kotlin version to 1.5.10 in order for compose to work.

```
e: This version (1.0.0-beta08) of the Compose Compiler requires Kotlin version 1.5.10 but you appear to be using Kotlin version 1.5.0 which is not known to be compatible.  Please fix your configuration (or `suppressKotlinVersionCompatibilityCheck` but don't say I didn't warn you!).
```

**Comment by Shusshu** [comment]
@arnaudgiuliani could you cut a release asap? (you'll please a bunch of eager compose fans)

**Comment by arnaudgiuliani** [comment]
I push 3.0.3 for next week 👍

**Comment by pedromeep** [comment]
Waiting for 3.0.3 🙏

**Comment by arnaudgiuliani** [comment]
yep 👍 coming ...

**Comment by arnaudgiuliani** [comment]
Updated in `23d247344d25029323d4f62889499ef8ddae3838`
