### ISSUE TITLE
androidLogger() doesn't work with Kotlin 1.6

### ISSUE THREAD

**Issue by Tuccro** [InsertKoinIO/koin#1216]
>     java.lang.NoSuchMethodError: No static method toDouble-impl(JLjava/util/concurrent/TimeUnit;)D in class Lkotlin/time/Duration; or its super classes (declaration of 'kotlin.time.Duration' appears in /data/data/com.example.app/code_cache/.overlay/base.apk/classes18.dex)
>         at org.koin.core.time.MeasureKt.measureDuration(Measure.kt:32)
>         at org.koin.core.KoinApplication.modules(KoinApplication.kt:59)

Application crashes on the start after a set of logger in Application class with the default parameter "level: Level = Level.INFO":

> startKoin {
>             androidLogger()

I think it's obvious, the problem is at **org.koin.core.time.MeasureKt.measureDuration(Measure.kt:32)** and becomes just in case when the logging level is lower than Level.ERROR.

**Comment by egorikftp** [comment]
Duplicate of https://github.com/InsertKoinIO/koin/issues/1188
