### PR TITLE
Fix build with Kotlin 1.3.70.

### LINKED ISSUE #740: Koin MonoClock class not found with Kotlin 1.3.70
**Describe the bug**
An app with Koin 2.1.0 or 2.1.1 will crash at runtime with:

```
2020-03-03 11:48:45.259 18449-18449/com.example.base E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.base, PID: 18449
    java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/time/MonoClock;
        at org.koin.core.time.MeasureKt.measureDuration(Measure.kt:31)
        at org.koin.core.KoinApplication.modules(KoinApplication.kt:60)
        at com.example.base.App$startDependencyInjection$1.invoke(App.kt:23)
        at com.example.base.App$startDependencyInjection$1.invoke(App.kt:11)
        at org.koin.core.context.ContextFunctionsKt.startKoin(ContextFunctions.kt:39)
        at org.koin.core.context.ContextFunctionsKt.startKoin$default(ContextFunctions.kt:35)
        at com.example.base.App.startDependencyInjection(App.kt:20)
        at com.example.base.App.onCreate(App.kt:15)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6601)
        at android.app.ActivityThread.access$1300(ActivityThread.java:226)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1886)
    	at android.os.Handler.dispatchMessage(Ha
```

after upgrading to Kotlin 1.3.70.

**To Reproduce**
1. Create a simple Koin app with at least one module.
2. Upgrade Kotlin to 1.3.70
3. Run App.

**Expected behavior**
Should not crash.

**Koin project used and used version (please complete the following information):**
 [e.g]: `koin-core version 0.9.2`

koin-android version 2.1.0 or 2.1.1

### PR DESCRIPTION
**Pull request by trashkalmar**
Fixes #740

### CODE REVIEW

**Comment by arnaudgiuliani** [comment]
Yes, exact. Timing API ... :/
Thanks
