### ISSUE TITLE
3.1.0 breaks the build when parametersOf is used from Java, unable to use static import

### ISSUE THREAD

**Issue by henningBunk** [InsertKoinIO/koin#1116]
**Describe the bug**
I cannot build my app after updating from 3.0.2 to 3.1.0. Sadly I got a still Java files left, in one of them I use Koin with injected parameters. After the update I get an error:

    app/modulesrc/main/java/package/MainActivity.java:140: error: static import only from classes and interfaces
    import static org.koin.core.parameter.DefinitionParametersKt.parametersOf;
    ^ IDLE
    > Task :components:kaptFreeDebugKotlin FAILED
    
    FAILURE: Build failed with an exception.

So I cannot use paramatersOf in Java files..

**To Reproduce**
1. Create a Java file
2. Add the import `import static org.koin.core.parameter.DefinitionParametersKt.parametersOf;`
3. Try to build

**Expected behavior**
The build does not fail and the dependency gets injected with the given parameter.

**Koin project used and used version (please complete the following information):**
 [e.g]: `koin-core version 3.1.0`

**Additional moduleDefinition**
Add any other moduleDefinition about the problem here.

**Comment by arnaudgiuliani** [comment]
Just tried `import static org.koin.core.parameter.ParametersHolderKt.parametersOf;` with `parametersOf(sessionScope);`

It's ok for me 🤔

**Comment by henningBunk** [comment]
Thank you for your reply. This is really weird. 

I noticed that you are using `import static org.koin.core.parameter.ParametersHolderKt.parametersOf;` while I was using `import static org.koin.core.parameter.DefinitionParametersKt.parametersOf;` which worked fine until 3.1.0.

Switching the import to `ParametersHolderKt` gets rid of the error for that import but I have another failing static import now. This time the source I am importing is a static string from a java file from my app. When I move that string into a kotlin file the error is gone and I can build.

So for now my problem is gone, please feel free to close the ticket.

I think though that I don't have the option anymore to make a static import in java from another java file. Not that I am planning to need this anymore, but I still I am curious why this could be.

**Comment by arnaudgiuliani** [comment]
Thanks
