### ISSUE TITLE
java.lang.NoClassDefFoundError version 2.0.1

### ISSUE THREAD

**Issue by Xolcars** [InsertKoinIO/koin#570]
Hi, i have a problem with Koin

The errors occurs when the app starts, on Application class.

This is how i define the modules:
```
val networkModule = module {
    factory<Interceptor> {
        HttpLoggingInterceptor(HttpLoggingInterceptor.Logger { Log.d("API", it) })
            .setLevel(HttpLoggingInterceptor.Level.BODY)
    }

    factory { Interceptor(prefs = get()) }

    factory {
        OkHttpClient.Builder()
            .addInterceptor(get<Interceptor>())
            .addInterceptor(get<HttpLoggingInterceptor>()).build()
    }

    single {
        Retrofit.Builder()
            .client(get<OkHttpClient>())
            .baseUrl(BuildConfig.BASE_URL)
            .addConverterFactory(GsonConverterFactory.create())
            .addCallAdapterFactory(CoroutineCallAdapterFactory())
            .build()
    }

    factory { get<Retrofit>().create<Service>() }
}
```
```
val preferencesModule = module {
    factory { Prefs(get()) }
}
```

And this is how start Koin:
```
override fun onCreate() {
        super.onCreate()
        startKoin {
            androidLogger()
            androidContext(this@App)
            modules(appComponent)
        }
    }
```

I got the next error:
```
Process: es.vanadis.utg_estaxi, PID: 30406
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/koin/core/context/GlobalContextKt;
        at es.vanadis.utg_estaxi.App.onCreate(App.kt:13)
...
```

I use this version: `implementation 'org.koin:koin-android:2.0.1'`

I have no idea why occurs that, some help?

**Comment by jeziellago** [comment]
@Xolcars could you show the code to `appComponent`?

**Comment by Xolcars** [comment]
appComponentCode:
`val appComponent = listOf(networkModule, repositoryModule, preferencesModule)
`

And the third module code:
```
val repositoryModule = module {
    factory { Repository(service = get(), context = get()) }
}
```

**Comment by jeziellago** [comment]
@Xolcars you're finding for `get<HttpLoggingInterceptor>()`, but providing `factory<Interceptor>`.
Try it:
```
factory {
        HttpLoggingInterceptor(HttpLoggingInterceptor.Logger { Log.d("API", it) })
            .setLevel(HttpLoggingInterceptor.Level.BODY)
 }
```

**Comment by Xolcars** [comment]
still not work =(
I get the same error

**Comment by Xolcars** [comment]
Also, I have observed that the app compiles perfectly in Android 9 or higher, only crash on versions lower than this one.

**Comment by Orgmir** [comment]
@Xolcars Could you give us a reason for closing this issue? I find myself having the same problem after updating to 2.0.1
